# Generated by Django 3.1.2 on 2020-10-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFacebook', '0002_auto_20201022_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
