# Generated by Django 3.1.2 on 2020-10-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFacebook', '0003_auto_20201022_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='username',
            new_name='Username',
        ),
    ]
