# Generated by Django 3.1.2 on 2020-10-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFacebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='type',
            new_name='username',
        ),
    ]
