# Generated by Django 3.1.2 on 2020-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFacebook', '0005_auto_20201022_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='Username',
            field=models.CharField(max_length=100),
        ),
    ]
